// <auto-generated />
namespace AssWebApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addingvehiculeattributes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingvehiculeattributes));
        
        string IMigrationMetadata.Id
        {
            get { return "201602012158570_adding vehicule attributes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
